INSERT INTO `country` (`name`, `country_code`) VALUES ("Afghanistan", 93);
INSERT INTO `country` (`name`, `country_code`) VALUES ("Aland Islands", 358);
INSERT INTO `country` (`name`, `country_code`) VALUES ("Albania", 355);
INSERT INTO `country` (`name`, `country_code`) VALUES ("Algeria", 213);
INSERT INTO `country` (`name`, `country_code`) VALUES ("American Samoa", 1);
INSERT INTO `country` (`name`, `country_code`) VALUES ("Andorra", 376);
INSERT INTO `country` (`name`, `country_code`) VALUES ("Angola", 244);
INSERT INTO `country` (`name`, `country_code`) VALUES ("Anguilla", 1);
INSERT INTO `country` (`name`, `country_code`) VALUES ("Antarctica", 672);
INSERT INTO `country` (`name`, `country_code`) VALUES ("Antigua and Barbuda", 1);
INSERT INTO `country` (`name`, `country_code`) VALUES ("Argentina", 54);
INSERT INTO `country` (`name`, `country_code`) VALUES ("Armenia", 374);
INSERT INTO `country` (`name`, `country_code`) VALUES ("Aruba", 297);
INSERT INTO `country` (`name`, `country_code`) VALUES ("Ascension Island", 247);
INSERT INTO `country` (`name`, `country_code`) VALUES ("Australia", 61);
INSERT INTO `country` (`name`, `country_code`) VALUES ("Austria", 43);
INSERT INTO `country` (`name`, `country_code`) VALUES ("Azerbaijan", 994);
INSERT INTO `country` (`name`, `country_code`) VALUES ("Bahamas", 1);
INSERT INTO `country` (`name`, `country_code`) VALUES ("Bahrain", 973);
INSERT INTO `country` (`name`, `country_code`) VALUES ("Bangladesh", 880);
INSERT INTO `country` (`name`, `country_code`) VALUES ("Barbados", 1);
INSERT INTO `country` (`name`, `country_code`) VALUES ("Belarus", 375);
INSERT INTO `country` (`name`, `country_code`) VALUES ("Belgium", 32);
INSERT INTO `country` (`name`, `country_code`) VALUES ("Belize", 501);
INSERT INTO `country` (`name`, `country_code`) VALUES ("Benin", 229);
INSERT INTO `country` (`name`, `country_code`) VALUES ("Bermuda", 1);
INSERT INTO `country` (`name`, `country_code`) VALUES ("Bhutan", 975);
INSERT INTO `country` (`name`, `country_code`) VALUES ("Bolivia", 591);
INSERT INTO `country` (`name`, `country_code`) VALUES ("Bosnia and Herzegovina", 387);
INSERT INTO `country` (`name`, `country_code`) VALUES ("Botswana", 267);
INSERT INTO `country` (`name`, `country_code`) VALUES ("Brazil", 55);
INSERT INTO `country` (`name`, `country_code`) VALUES ("British Indian Ocean Territory", 246);
INSERT INTO `country` (`name`, `country_code`) VALUES ("Brunei Darussalam", 673);
INSERT INTO `country` (`name`, `country_code`) VALUES ("Burkina Faso", 226);
INSERT INTO `country` (`name`, `country_code`) VALUES ("Burundi", 257);
INSERT INTO `country` (`name`, `country_code`) VALUES ("Cambodia", 855);
INSERT INTO `country` (`name`, `country_code`) VALUES ("Cameroon", 237);
INSERT INTO `country` (`name`, `country_code`) VALUES ("Canada", 1);
INSERT INTO `country` (`name`, `country_code`) VALUES ("Canary Islands", 34);
INSERT INTO `country` (`name`, `country_code`) VALUES ("Cape Verde", 238);
INSERT INTO `country` (`name`, `country_code`) VALUES ("Cayman Islands", 1);
INSERT INTO `country` (`name`, `country_code`) VALUES ("Central African Republic", 236);
INSERT INTO `country` (`name`, `country_code`) VALUES ("Ceuta and Melilla", 34);
INSERT INTO `country` (`name`, `country_code`) VALUES ("Chad", 235);
INSERT INTO `country` (`name`, `country_code`) VALUES ("Chile", 56);
INSERT INTO `country` (`name`, `country_code`) VALUES ("China", 86);
INSERT INTO `country` (`name`, `country_code`) VALUES ("Christmas Island", 61);
INSERT INTO `country` (`name`, `country_code`) VALUES ("Cocos (Keeling) Island", 61);
INSERT INTO `country` (`name`, `country_code`) VALUES ("Colombia", 57);
INSERT INTO `country` (`name`, `country_code`) VALUES ("Comoros", 269);
INSERT INTO `country` (`name`, `country_code`) VALUES ("Congo", 242);
INSERT INTO `country` (`name`, `country_code`) VALUES ("Congo- Democratic Republic of the", 243);
INSERT INTO `country` (`name`, `country_code`) VALUES ("Cook Islands", 682);
INSERT INTO `country` (`name`, `country_code`) VALUES ("Costa Rica", 506);
INSERT INTO `country` (`name`, `country_code`) VALUES ("Côte D'Ivoire", 225);
INSERT INTO `country` (`name`, `country_code`) VALUES ("Croatia", 385);
INSERT INTO `country` (`name`, `country_code`) VALUES ("Cuba", 53);
INSERT INTO `country` (`name`, `country_code`) VALUES ("Cyprus- Republic of", 357);
INSERT INTO `country` (`name`, `country_code`) VALUES ("Cyprus- Turkish Republic of Northern", 90);
INSERT INTO `country` (`name`, `country_code`) VALUES ("Czech Republic", 420);
INSERT INTO `country` (`name`, `country_code`) VALUES ("Denmark", 45);
INSERT INTO `country` (`name`, `country_code`) VALUES ("Djibouti", 253);
INSERT INTO `country` (`name`, `country_code`) VALUES ("Dominica", 1);
INSERT INTO `country` (`name`, `country_code`) VALUES ("Dominican Republic", 1);
INSERT INTO `country` (`name`, `country_code`) VALUES ("Ecuador", 593);
INSERT INTO `country` (`name`, `country_code`) VALUES ("Egypt", 20);
INSERT INTO `country` (`name`, `country_code`) VALUES ("El Salvador", 503);
INSERT INTO `country` (`name`, `country_code`) VALUES ("Equatorial Guinea", 240);
INSERT INTO `country` (`name`, `country_code`) VALUES ("Eritrea", 291);
INSERT INTO `country` (`name`, `country_code`) VALUES ("Estonia", 372);
INSERT INTO `country` (`name`, `country_code`) VALUES ("Ethiopia", 251);
INSERT INTO `country` (`name`, `country_code`) VALUES ("Falkland Islands", 500);
INSERT INTO `country` (`name`, `country_code`) VALUES ("Faroe Islands", 298);
INSERT INTO `country` (`name`, `country_code`) VALUES ("Fiji", 679);
INSERT INTO `country` (`name`, `country_code`) VALUES ("Finland", 358);
INSERT INTO `country` (`name`, `country_code`) VALUES ("France", 33);
INSERT INTO `country` (`name`, `country_code`) VALUES ("French Guiana", 594);
INSERT INTO `country` (`name`, `country_code`) VALUES ("French Polynesia", 689);
INSERT INTO `country` (`name`, `country_code`) VALUES ("French Southern and Antarctic Lands", 262);
INSERT INTO `country` (`name`, `country_code`) VALUES ("Gabon", 241);
INSERT INTO `country` (`name`, `country_code`) VALUES ("Gambia", 220);
INSERT INTO `country` (`name`, `country_code`) VALUES ("Georgia", 995);
INSERT INTO `country` (`name`, `country_code`) VALUES ("Germany", 49);
INSERT INTO `country` (`name`, `country_code`) VALUES ("Ghana", 233);
INSERT INTO `country` (`name`, `country_code`) VALUES ("Gibraltar", 350);
INSERT INTO `country` (`name`, `country_code`) VALUES ("Greece", 30);
INSERT INTO `country` (`name`, `country_code`) VALUES ("Greenland", 299);
INSERT INTO `country` (`name`, `country_code`) VALUES ("Grenada", 1);
INSERT INTO `country` (`name`, `country_code`) VALUES ("Guadeloupe", 590);
INSERT INTO `country` (`name`, `country_code`) VALUES ("Guam", 1);
INSERT INTO `country` (`name`, `country_code`) VALUES ("Guatemala", 502);
INSERT INTO `country` (`name`, `country_code`) VALUES ("Guernsey", 44);
INSERT INTO `country` (`name`, `country_code`) VALUES ("Guinea", 224);
INSERT INTO `country` (`name`, `country_code`) VALUES ("Guinea-Bissau", 245);
INSERT INTO `country` (`name`, `country_code`) VALUES ("Guyana", 592);
INSERT INTO `country` (`name`, `country_code`) VALUES ("Haiti", 509);
INSERT INTO `country` (`name`, `country_code`) VALUES ("Holy See (Vatican City State)", 39);
INSERT INTO `country` (`name`, `country_code`) VALUES ("Honduras", 504);
INSERT INTO `country` (`name`, `country_code`) VALUES ("Hong Kong", 852);
INSERT INTO `country` (`name`, `country_code`) VALUES ("Hungary", 36);
INSERT INTO `country` (`name`, `country_code`) VALUES ("Iceland", 354);
INSERT INTO `country` (`name`, `country_code`) VALUES ("India", 91);
INSERT INTO `country` (`name`, `country_code`) VALUES ("Indonesia", 62);
INSERT INTO `country` (`name`, `country_code`) VALUES ("Iran", 98);
INSERT INTO `country` (`name`, `country_code`) VALUES ("Iraq", 964);
INSERT INTO `country` (`name`, `country_code`) VALUES ("Ireland", 353);
INSERT INTO `country` (`name`, `country_code`) VALUES ("Isle of Man", 44);
INSERT INTO `country` (`name`, `country_code`) VALUES ("Israel", 972);
INSERT INTO `country` (`name`, `country_code`) VALUES ("Italy", 39);
INSERT INTO `country` (`name`, `country_code`) VALUES ("Jamaica", 1);
INSERT INTO `country` (`name`, `country_code`) VALUES ("Japan", 81);
INSERT INTO `country` (`name`, `country_code`) VALUES ("Jersey", 44);
INSERT INTO `country` (`name`, `country_code`) VALUES ("Jordan", 962);
INSERT INTO `country` (`name`, `country_code`) VALUES ("Kazakhstan", 7);
INSERT INTO `country` (`name`, `country_code`) VALUES ("Kenya", 254);
INSERT INTO `country` (`name`, `country_code`) VALUES ("Kiribati", 686);
INSERT INTO `country` (`name`, `country_code`) VALUES ("Korea- Democratic People's Republic of", 850);
INSERT INTO `country` (`name`, `country_code`) VALUES ("Korea- Republic of", 82);
INSERT INTO `country` (`name`, `country_code`) VALUES ("Kuwait", 965);
INSERT INTO `country` (`name`, `country_code`) VALUES ("Kyrgyz Republic", 996);
INSERT INTO `country` (`name`, `country_code`) VALUES ("Laos", 856);
INSERT INTO `country` (`name`, `country_code`) VALUES ("Latvia", 371);
INSERT INTO `country` (`name`, `country_code`) VALUES ("Lebanon", 961);
INSERT INTO `country` (`name`, `country_code`) VALUES ("Lesotho", 266);
INSERT INTO `country` (`name`, `country_code`) VALUES ("Liberia", 231);
INSERT INTO `country` (`name`, `country_code`) VALUES ("Libya", 218);
INSERT INTO `country` (`name`, `country_code`) VALUES ("Liechtenstein", 423);
INSERT INTO `country` (`name`, `country_code`) VALUES ("Lithuania", 370);
INSERT INTO `country` (`name`, `country_code`) VALUES ("Luxembourg", 352);
INSERT INTO `country` (`name`, `country_code`) VALUES ("Macao", 853);
INSERT INTO `country` (`name`, `country_code`) VALUES ("Macedonia", 389);
INSERT INTO `country` (`name`, `country_code`) VALUES ("Madagascar", 261);
INSERT INTO `country` (`name`, `country_code`) VALUES ("Malawi", 265);
INSERT INTO `country` (`name`, `country_code`) VALUES ("Malaysia", 60);
INSERT INTO `country` (`name`, `country_code`) VALUES ("Maldives", 960);
INSERT INTO `country` (`name`, `country_code`) VALUES ("Mali", 223);
INSERT INTO `country` (`name`, `country_code`) VALUES ("Malta", 356);
INSERT INTO `country` (`name`, `country_code`) VALUES ("Marshall Islands", 692);
INSERT INTO `country` (`name`, `country_code`) VALUES ("Martinique", 596);
INSERT INTO `country` (`name`, `country_code`) VALUES ("Mauritania", 222);
INSERT INTO `country` (`name`, `country_code`) VALUES ("Mauritius", 230);
INSERT INTO `country` (`name`, `country_code`) VALUES ("Mayotte", 269);
INSERT INTO `country` (`name`, `country_code`) VALUES ("Mexico", 52);
INSERT INTO `country` (`name`, `country_code`) VALUES ("Micronesia", 691);
INSERT INTO `country` (`name`, `country_code`) VALUES ("Moldova", 373);
INSERT INTO `country` (`name`, `country_code`) VALUES ("Monaco", 377);
INSERT INTO `country` (`name`, `country_code`) VALUES ("Mongolia", 976);
INSERT INTO `country` (`name`, `country_code`) VALUES ("Montenegro", 382);
INSERT INTO `country` (`name`, `country_code`) VALUES ("Montserrat", 1);
INSERT INTO `country` (`name`, `country_code`) VALUES ("Morocco", 212);
INSERT INTO `country` (`name`, `country_code`) VALUES ("Mozambique", 258);
INSERT INTO `country` (`name`, `country_code`) VALUES ("Myanmar", 95);
INSERT INTO `country` (`name`, `country_code`) VALUES ("Namibia", 264);
INSERT INTO `country` (`name`, `country_code`) VALUES ("Nauru", 674);
INSERT INTO `country` (`name`, `country_code`) VALUES ("Nepal", 977);
INSERT INTO `country` (`name`, `country_code`) VALUES ("Netherlands", 31);
INSERT INTO `country` (`name`, `country_code`) VALUES ("Netherlands Antilles", 599);
INSERT INTO `country` (`name`, `country_code`) VALUES ("New Caledonia", 687);
INSERT INTO `country` (`name`, `country_code`) VALUES ("New Zealand", 64);
INSERT INTO `country` (`name`, `country_code`) VALUES ("Nicaragua", 505);
INSERT INTO `country` (`name`, `country_code`) VALUES ("Niger", 227);
INSERT INTO `country` (`name`, `country_code`) VALUES ("Nigeria", 234);
INSERT INTO `country` (`name`, `country_code`) VALUES ("Niue", 683);
INSERT INTO `country` (`name`, `country_code`) VALUES ("Norfolk Island", 672);
INSERT INTO `country` (`name`, `country_code`) VALUES ("Northern Mariana Islands", 1);
INSERT INTO `country` (`name`, `country_code`) VALUES ("Norway", 47);
INSERT INTO `country` (`name`, `country_code`) VALUES ("Oman", 968);
INSERT INTO `country` (`name`, `country_code`) VALUES ("Pakistan", 92);
INSERT INTO `country` (`name`, `country_code`) VALUES ("Palau", 680);
INSERT INTO `country` (`name`, `country_code`) VALUES ("Palestine", 970);
INSERT INTO `country` (`name`, `country_code`) VALUES ("Panama", 507);
INSERT INTO `country` (`name`, `country_code`) VALUES ("Papua New Guinea", 675);
INSERT INTO `country` (`name`, `country_code`) VALUES ("Paraguay", 595);
INSERT INTO `country` (`name`, `country_code`) VALUES ("Peru", 51);
INSERT INTO `country` (`name`, `country_code`) VALUES ("Philippines", 63);
INSERT INTO `country` (`name`, `country_code`) VALUES ("Pitcairn", 872);
INSERT INTO `country` (`name`, `country_code`) VALUES ("Poland", 48);
INSERT INTO `country` (`name`, `country_code`) VALUES ("Portugal", 351);
INSERT INTO `country` (`name`, `country_code`) VALUES ("Puerto Rico", 1);
INSERT INTO `country` (`name`, `country_code`) VALUES ("Qatar", 974);
INSERT INTO `country` (`name`, `country_code`) VALUES ("Réunion", 262);
INSERT INTO `country` (`name`, `country_code`) VALUES ("Romania", 40);
INSERT INTO `country` (`name`, `country_code`) VALUES ("Russian Federation", 7);
INSERT INTO `country` (`name`, `country_code`) VALUES ("Rwanda", 250);
INSERT INTO `country` (`name`, `country_code`) VALUES ("Saint Helena", 290);
INSERT INTO `country` (`name`, `country_code`) VALUES ("Saint Kitts and Nevis", 1);
INSERT INTO `country` (`name`, `country_code`) VALUES ("Saint Lucia", 1);
INSERT INTO `country` (`name`, `country_code`) VALUES ("Saint Pierre and Miquelon", 508);
INSERT INTO `country` (`name`, `country_code`) VALUES ("Saint Vincent and the Grenadines", 1);
INSERT INTO `country` (`name`, `country_code`) VALUES ("Samoa", 685);
INSERT INTO `country` (`name`, `country_code`) VALUES ("San Marino", 378);
INSERT INTO `country` (`name`, `country_code`) VALUES ("São Tome and Principe", 239);
INSERT INTO `country` (`name`, `country_code`) VALUES ("Saudi Arabia", 966);
INSERT INTO `country` (`name`, `country_code`) VALUES ("Senegal", 221);
INSERT INTO `country` (`name`, `country_code`) VALUES ("Serbia", 381);
INSERT INTO `country` (`name`, `country_code`) VALUES ("Seychelles", 248);
INSERT INTO `country` (`name`, `country_code`) VALUES ("Sierra Leone", 232);
INSERT INTO `country` (`name`, `country_code`) VALUES ("Singapore", 65);
INSERT INTO `country` (`name`, `country_code`) VALUES ("Slovakia", 421);
INSERT INTO `country` (`name`, `country_code`) VALUES ("Slovenia", 386);
INSERT INTO `country` (`name`, `country_code`) VALUES ("Solomon Islands", 677);
INSERT INTO `country` (`name`, `country_code`) VALUES ("Somalia", 252);
INSERT INTO `country` (`name`, `country_code`) VALUES ("Somaliland", 252);
INSERT INTO `country` (`name`, `country_code`) VALUES ("South Africa", 27);
INSERT INTO `country` (`name`, `country_code`) VALUES ("Spain", 34);
INSERT INTO `country` (`name`, `country_code`) VALUES ("Sri Lanka", 94);
INSERT INTO `country` (`name`, `country_code`) VALUES ("Sudan", 249);
INSERT INTO `country` (`name`, `country_code`) VALUES ("Suriname", 597);
INSERT INTO `country` (`name`, `country_code`) VALUES ("Svalbard and Jan Mayen", 47);
INSERT INTO `country` (`name`, `country_code`) VALUES ("Swaziland", 268);
INSERT INTO `country` (`name`, `country_code`) VALUES ("Sweden", 46);
INSERT INTO `country` (`name`, `country_code`) VALUES ("Switzerland", 41);
INSERT INTO `country` (`name`, `country_code`) VALUES ("Syria", 963);
INSERT INTO `country` (`name`, `country_code`) VALUES ("Taiwan", 886);
INSERT INTO `country` (`name`, `country_code`) VALUES ("Tajikistan", 992);
INSERT INTO `country` (`name`, `country_code`) VALUES ("Tanzania", 255);
INSERT INTO `country` (`name`, `country_code`) VALUES ("Thailand", 66);
INSERT INTO `country` (`name`, `country_code`) VALUES ("Timor-Leste", 670);
INSERT INTO `country` (`name`, `country_code`) VALUES ("Togo", 228);
INSERT INTO `country` (`name`, `country_code`) VALUES ("Tokelau", 690);
INSERT INTO `country` (`name`, `country_code`) VALUES ("Tonga", 676);
INSERT INTO `country` (`name`, `country_code`) VALUES ("Trinidad and Tobago", 1);
INSERT INTO `country` (`name`, `country_code`) VALUES ("Tristan da Cunha", 290);
INSERT INTO `country` (`name`, `country_code`) VALUES ("Tunisia", 216);
INSERT INTO `country` (`name`, `country_code`) VALUES ("Turkey", 90);
INSERT INTO `country` (`name`, `country_code`) VALUES ("Turkmenistan", 993);
INSERT INTO `country` (`name`, `country_code`) VALUES ("Turks and Caicos Islands", 1);
INSERT INTO `country` (`name`, `country_code`) VALUES ("Tuvalu", 688);
INSERT INTO `country` (`name`, `country_code`) VALUES ("Uganda", 256);
INSERT INTO `country` (`name`, `country_code`) VALUES ("Ukraine", 380);
INSERT INTO `country` (`name`, `country_code`) VALUES ("United Arab Emirates", 971);
INSERT INTO `country` (`name`, `country_code`) VALUES ("United Kingdom", 44);
INSERT INTO `country` (`name`, `country_code`) VALUES ("United States", 1);
INSERT INTO `country` (`name`, `country_code`) VALUES ("United States Minor Outlying Islands", 699);
INSERT INTO `country` (`name`, `country_code`) VALUES ("Uruguay", 598);
INSERT INTO `country` (`name`, `country_code`) VALUES ("Uzbekistan", 998);
INSERT INTO `country` (`name`, `country_code`) VALUES ("Vanuatu", 678);
INSERT INTO `country` (`name`, `country_code`) VALUES ("Venezuela", 58);
INSERT INTO `country` (`name`, `country_code`) VALUES ("Viet Nam", 84);
INSERT INTO `country` (`name`, `country_code`) VALUES ("Virgin Islands- British", 1);
INSERT INTO `country` (`name`, `country_code`) VALUES ("Virgin Islands- U.S.", 1);
INSERT INTO `country` (`name`, `country_code`) VALUES ("Wallis and Futuna Islands", 681);
INSERT INTO `country` (`name`, `country_code`) VALUES ("Western Sahara", 212);
INSERT INTO `country` (`name`, `country_code`) VALUES ("Yemen", 967);
INSERT INTO `country` (`name`, `country_code`) VALUES ("Zambia", 260);
INSERT INTO `country` (`name`, `country_code`) VALUES ("Zimbabwe", 263);
